name: Upload React to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    #step 1: checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3
    
    #step 2: set up node.js 
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    #step 3: install dependencies / pass through environment variable(s)
    - name: Intstall Dependencies
      run: |
          echo "VITE_DOMAIN_URL=${{ secrets.VITE_DOMAIN_URL }}" > .env
          echo "VITE_CONFIG=PROD" >> .env
          npm install

    #step 4. Run Tests
    - name: Run Tests
      run: npm run test:ci

    #step 5: Build for Production
    - name:  Build for Production
      env: 
        VITE_DOMAIN_URL: ${{ secrets.VITE_DOMAIN_URL }}
        VITE_CONFIG: 'PROD'
      run: npm run build

    #step 6: Sync build folder to s3
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.git*/*'
      env:
        SOURCE_DIR: ./dist #only upload the dist folder
        AWS_REGION: us-east-1
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
